FROM ubuntu:xenial

RUN apt-get update && \
    apt-get install -y libxcb1 libxcb-shape0 libxcb-xfixes0 libasound2 libass5 libmp3lame0 libvdpau1 && \
    rm -rf /var/lib/apt/lists/*

ADD ffmpeg /bin/ffmpeg
ADD ffprobe /bin/ffprobe
ADD ffserver /bin/ffserver

VOLUME /data
